Add context to tree
DSD-DBS/capellambse-context-diagrams pull request #68
Opened 2024-01-18 09:32 UTC by huyenngn

2024-02-07 07:48 UTC, ewuerger requested changes
Just the few points and then LGTM.

2024-02-07 07:48 UTC, ewuerger commented on capellambse_context_diagrams/context.py
> +        add_context(layout)
`add_context` is just called in the `ClassTreeDiagram` creator function. Don't we need context for all context diagram types? Please add context in all of the diagrams.

2024-02-07 07:48 UTC, ewuerger commented on capellambse_context_diagrams/context.py
> +        child["context"] = list(ids)  # type: ignore[typeddict-unknown-key]
This is a very simple algorithm calculating a single context/set of IDs. Currently all context diagram types are just one connected graph. So algorithmically this is fine. We still need a doc-string here.

2024-02-09 13:23 UTC, ewuerger requested changes
Almost.

2024-02-09 13:23 UTC, ewuerger commented on capellambse_context_diagrams/context.py
> +            if cobj["type"] == "node":
```suggestion
            if cobj["type"] in {"node", "port", "junction", "edge"}:
```

2024-02-09 13:23 UTC, ewuerger commented on capellambse_context_diagrams/context.py
> +        if child["type"] == "node" or child["type"] == "edge":
```suggestion
        if cobj["type"] in {"node", "port", "junction", "edge"}:
```

2024-02-12 09:47 UTC, Wuestengecko commented on capellambse_context_diagrams/collectors/dataflow_view.py
> +"""..."""
Bad docstring. Either remove or fix it.

2024-02-12 11:56 UTC, Wuestengecko commented on capellambse_context_diagrams/collectors/dataflow_view.py
There are also several commits marked "wip" still in the history, which should be squashed or rebased away otherwise before merging. It's not a valid "conventional commits" type as per our standard config (and, mainly, it just looks bad and makes reading / searching the history much less enjoyable).

<sup>(I'm posting this as file comment so we can keep track and resolve it once it's done.)</sup>

2024-02-12 12:29 UTC, ewuerger commented on capellambse_context_diagrams/collectors/dataflow_view.py
Thanks for the reminder. I intended to squash all commits into one when the PR is ready to be merged.

2024-02-12 12:32 UTC, ewuerger approved these changes
LGTM.

2024-02-12 12:34 UTC, Wuestengecko commented on capellambse_context_diagrams/collectors/dataflow_view.py
> so we can […] resolve it once it's done

> resolved immediately

:upside_down_face: 

(Apart from that - what a great way to make the history feature even less useful. Look at how many different things happened here. :P )

2024-02-12 12:35 UTC, merged